DROP TABLE DUPCHECKRULEIF EXISTS;
CREATE TABLE DUPCHECKRULE(
DUPCHECK_RULE_ID	NUMERIC,
TRANSACTION_TYPE	VARCHAR(100),
TRANSACTION_SUB_TYPE	VARCHAR(100),
DUPCHECK_TYPE		VARCHAR(1)
FIELD_NAME		VARCHAR(500),
CREATED_ON		TIMESTAMP,
UPDATED_ON		TIMESTAMP
);